// <auto-generated />
using JwtAudience;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace JwtAudience.Migrations
{
    [DbContext(typeof(AudienceDbContext))]
    partial class AudienceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("JwtAudience.BlackRecord", b =>
                {
                    b.Property<string>("Jti")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserId");

                    b.HasKey("Jti");

                    b.ToTable("BlackRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
